import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // The Next.js app no longer sits at the repo root, so the rules that look
    // for it (such as no-html-link-for-pages) need to be told where it is.
    settings: { next: { rootDir: "apps/web" } },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next, widened for the workspaces.
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/dist/**",
    "**/next-env.d.ts",
    // Generated by the test runs.
    "**/coverage/**",
  ]),
]);

export default eslintConfig;
